// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWcOHJSuWYFLjJC9l1grhMtymlolGdgjs',
    appId: '1:95038094021:android:84cf9895696fd5217e0eac',
    messagingSenderId: '95038094021',
    projectId: 'masyu-app-by-unboringcompany',
    storageBucket: 'masyu-app-by-unboringcompany.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD5FD1QAZeKYTk_-MF6niLX-QvuazwDB4',
    appId: '1:95038094021:ios:20ffa72efc6effff7e0eac',
    messagingSenderId: '95038094021',
    projectId: 'masyu-app-by-unboringcompany',
    storageBucket: 'masyu-app-by-unboringcompany.appspot.com',
    iosClientId:
        '95038094021-cni66367mkhkc3669aqg5kfo7hdgce0p.apps.googleusercontent.com',
    iosBundleId: 'com.example.masyuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD5FD1QAZeKYTk_-MF6niLX-QvuazwDB4',
    appId: '1:95038094021:ios:61895f2b8b75422d7e0eac',
    messagingSenderId: '95038094021',
    projectId: 'masyu-app-by-unboringcompany',
    storageBucket: 'masyu-app-by-unboringcompany.appspot.com',
    iosClientId:
        '95038094021-h3am1hhvtm8dvg1tbivhtdvb4s6p73ah.apps.googleusercontent.com',
    iosBundleId: 'com.example.masyuApp.RunnerTests',
  );
}
